# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 11:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_codes',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='verification codes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='clash_id',
            field=models.CharField(max_length=256, verbose_name='clash id'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cup_numbers',
            field=models.PositiveIntegerField(verbose_name='cup numbers'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.PositiveSmallIntegerField(verbose_name='level'),
        ),
    ]
