# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_avatars/', verbose_name='avatar'),
        ),
    ]
